### ISSUE TITLE
EOS balance is wrong

### ISSUE THREAD

**Issue by changmyeong** [hunterlong/tokenbalance#13]
I have 221 eos.
but, My EOS balance is 0 on your server.

https://api.tokenbalance.com/token/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0/0x19d3A5Bb1686dA95B8404632ba1c3aD79A87cBef

Running the tokenbalance server at local and tested it.
Then, It gave the correct result.

Please, Check your geth.ipc

**Comment by TrixieGrim** [comment]
We seem to be having the same issue 

There should be 150 in the wallet, and it's showing a 30 balance on your server.
Been almost an hour with no update

**Comment by hunterlong** [comment]
I've added more geth nodes to the Token Balance server cluster, so hopefully the balance is up-to-date with the current block. Your EOS seems to be correct now. I'll be adding more geth servers in the upcoming days. We should be good for now though.
