### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by TrixieGrim** [hunterlong/tokenbalance#14]
We are doing some testing and using the API from TokenBalance.
However the issue we are running into is that it is not updating in a timely manor.

For example, I have transferred 100 PLUM and 20 PLUM, on two separate transactions
but the balance is still only showing 30 PLUM from the previous days transactions.

If I hunt around on other sources, the transaction has already posted and shown.

Curious as to what the timing is for updates on your end.
Thank you!

**Comment by hunterlong** [comment]
I’ve been working on making a cluster of geth servers, right now it’s running 2 geth servers with 10 token balance app in a cluster. Both of the geth clusters are up to date with the current block, so my only idea is nginx is caching the responses. 

I have a couple issues I have to workout with token balance, I think I’ve solved the problem with scaling, but there does seems to be geth issues. I’ll comment back when I have an answer.

**Comment by hunterlong** [comment]
I've scaled the geth server cluster's up a bit. Should keep up-to-date now. Comment back if you have more issues with incorrect balances, and check if `block` in the JSON is the current ETH block.

**Comment by TrixieGrim** [comment]
Hey thanks for the help and quick response. It's appreciated

**Comment by hunterlong** [comment]
You got it. I recently made a server status page for Token Balance. Might be useful if you encounter server issues. 

[https://status.tokenbalance.com](https://status.tokenbalance.com)
