### ISSUE TITLE
Token Balance Issue 

### ISSUE THREAD

**Issue by sumitpatel93** [hunterlong/tokenbalance#15]
This issue is coming for the token balance,when we have following balances in any address like 100,120,2200,1000 it shows 1,12,22,1 respectively on giving the response.

As you can check on this address : 
0x0f1cbae928ae3073fad522c8fa902b7ff679d881
https://rinkeby.etherscan.io/token/0x53576813682009a4d35495e18f039067618b3e27#balances
ON GET request https://rinkeby.tokenbalance.com/token/0x53576813682009a4D35495e18f039067618B3e27/0x0f1cbae928ae3073fad522c8fa902b7ff679d881
I am getting token balance : 1 but I have 100 tokens
--

**Comment by hunterlong** [comment]
I just pushed an update to allow 0 decimals. I’ll update here once tests are passing correctly, after tests, the API servers will be updated.

**Comment by hunterlong** [comment]
This issue has been fixed and TokenBalance API's are now showing correct decimals for ERC20 token contracts that have 0 decimals set.
