### ISSUE TITLE
test.tokenbalance.com missing Allow Origin header

### ISSUE THREAD

**Issue by le4ker** [hunterlong/tokenbalance#16]
Hello,

From Postman the following request works:

`https://test.tokenbalance.com/token/0x3c52896bdd11cb76356b38236978f572333cd188/0x86549A6797F0c1fC7ABF5574dC9916EA57EF2825`

But when I'm issuing it from the browser it's being rejected due to CORS.

`$("button").click(function() {
  $("BUTTON").html("Loading");
  var token = $("#contract_address").val();
  var address = $("#eth_address").val();
  $.get("https://test.tokenbalance.com/token/" + token + "/" + address, function(data, status) {
    $("#token_name").html(data.name);
    $("#token_amount").html(data.balance + " " + data.symbol);
    $("#eth_balance").html(data.eth_balance + " ETH");
    $("BUTTON").html("Get Balance");
  }).catch(function(e) {
  	alert(e.statusText+" - unknown token");
  });
});
`

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://test.tokenbalance.com/token/0x3c52896bdd11cb76356b38236978f572333cd188/0x86549A6797F0c1fC7ABF5574dC9916EA57EF2825. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by hunterlong** [comment]
@le4ker  sorry about the delay, this issue has been fixed.
