### ISSUE TITLE
Would it be possible to use this as a library

### ISSUE THREAD

**Issue by BenKnigge** [hunterlong/tokenbalance#17]
Would it be possible to use this as a library from within another app with the get url being configurable?

**Comment by hunterlong** [comment]
Currently, no... since I have main.go, it will be built as a binary. I want to move the cmd to its own directory so users can use this as a golang package.

I’ll work on this, once it’s complete I’ll update this comment.

**Comment by hunterlong** [comment]
@BenKnigge , i've been wanting to do this for a while. You can try out the Token Balance golang package, a short example is on the Readme under [Golang Package](https://github.com/hunterlong/tokenbalance#use-as-golang-package)

🎉
