### ISSUE TITLE
Is there any contract for ETH?

### ISSUE THREAD

**Issue by Andrey4Dev** [hunterlong/tokenbalance#19]
Hello. How can I check ETH balance?

**Comment by hunterlong** [comment]
You can also view `eth_balance` in the JSON request like so:

[https://api.tokenbalance.com/token/0xa74476443119A942dE498590Fe1f2454d7D4aC0d/0xda0aed568d9a2dbdcbafc1576fedc633d28eee9a](https://api.tokenbalance.com/token/0xa74476443119A942dE498590Fe1f2454d7D4aC0d/0xda0aed568d9a2dbdcbafc1576fedc633d28eee9a)

### Output JSON
```json
{
"token": "0xa74476443119A942dE498590Fe1f2454d7D4aC0d",
"wallet": "0xda0AEd568D9A2dbDcBAFC1576fedc633d28EEE9a",
"name": "Golem Network Token",
"symbol": "GNT",
"balance": "5401731.086778292432427406",
"eth_balance": "0.985735366999999973",
"decimals": 18,
"block": 6611832
}
````
