### ISSUE TITLE
start tokenbalance is directory

### ISSUE THREAD

**Issue by fishmc** [hunterlong/tokenbalance#20]
go build github.com/hunterlong/tokenbalance/cmd: build output "cmd" already exists and is a directory

**Comment by hunterlong** [comment]
Hey @fishmc , I recommend trying out the Make command to make the build process a 1-liner.

```bash
make build
# This command will create the tokenbalance app
```
If you don't want to use make, the build command is:
```bash
VERSION=1.72
go build -ldflags="-X main.VERSION=$(VERSION)" -o tokenbalance -v ./cmd
```
