### ISSUE TITLE
inconsistent data

### ISSUE THREAD

**Issue by lrawiczNC** [hunterlong/tokenbalance#21]
you have an issues after the hard fork of robsten.

Here is an example: 
https://test.tokenbalance.com/balance/0x5cE6d0cD1D8aD36ADee2fb20C7705e2eAa77464a/0x470436CDBfaBb7217bCE4CB7d2EA75B441355Fac

should be 386 as shown in EtherScan
https://ropsten.etherscan.io/address/0x470436cdbfabb7217bce4cb7d2ea75b441355fac

**Comment by hunterlong** [comment]
hey @lrawiczNC , I've fixed this issue and updated the TokenBalance API's. The response for the URL you posted is now `386.0`, which seems to be correct.
