### ISSUE TITLE
API fails with SSL error

### ISSUE THREAD

**Issue by aphilsmith** [hunterlong/tokenbalance#3]
An error occurred during a connection to api.tokenbalance.com. Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP

**Comment by hunterlong** [comment]
fixed

**Comment by hunterlong** [comment]
sorry for the delay, been busy watching charts. haha 🎉

**Comment by hunterlong** [comment]
I recently made a server status page for Token Balance. Might be useful if you encounter server issues. 

[https://status.tokenbalance.com](https://status.tokenbalance.com)
