### ISSUE TITLE
Compile error at bind.NewBoundContract

### ISSUE THREAD

**Issue by alexcos20** [hunterlong/tokenbalance#4]
trying to compile:

/usr/lib/go-1.9/bin/go get
# github.com/hunterlong/tokenbalance
./tokens.go:104:30: not enough arguments in call to bind.NewBoundContract
        have (common.Address, abi.ABI, bind.ContractCaller, bind.ContractTransactor)
        want (common.Address, abi.ABI, bind.ContractCaller, bind.ContractTransactor, bind.ContractFilterer)

root@geth1:~/go/src/github.com/hunterlong/tokenbalance# /usr/lib/go-1.9/bin/go version
go version go1.9.2 linux/amd64

Thanks

**Comment by hunterlong** [comment]
The go package for Ethereum was recently updated. I've made a fix and it's working again.  

https://github.com/hunterlong/tokenbalance/commit/3850adfcec3fa345e52121cda13b0dce482b7a87#diff-17a54f44f0c3cb7e4515abf4e193ca5aR104
