### ISSUE TITLE
ERC20 constant type error

### ISSUE THREAD

**Issue by keysonZZZ** [hunterlong/tokenbalance#6]
Some Tokens, such as EOS, have different decimal or symbol type, which can  cause search error.It may need to be contained.:)

**Comment by nanmu42** [comment]
EOS has not implemented ERC20 interface quite correctly.

keyson Chou <notifications@github.com>于2018年4月14日周六 上午10:47写道：

**Comment by hunterlong** [comment]
Thanks @keysonZZZ - I made the patch for EOS, and updated the API servers. https://github.com/hunterlong/tokenbalance/commit/3f894f402c21df890f07af6841babd0e3bbc4a57
