### ISSUE TITLE
token information in rinkeby

### ISSUE THREAD

**Issue by jesuasir007** [hunterlong/tokenbalance#7]
how can i get token information from rinkeby test network?

**Comment by nanmu42** [comment]
You may run this service connected with a rinkeby node (Geth or Parity) by yourself.

**Comment by hunterlong** [comment]
After many many requests, I’ve started up a rinkeby testnet server. I’ll update this issue and readme once it’s online.

**Comment by hunterlong** [comment]
Alrighty, I have Rinkeby test network online now. The URL for Rinkeby token balance API is: 

`https://rinkeby.tokenbalance.com/token/CONTRACT/ADDRESS`

Test it out with: [https://rinkeby.tokenbalance.com/token/0x7295bb8709ec1c22b758a8119a4214ffed016323/0x4bfe074965f1e322e539b2f2995d611edc274d10](https://rinkeby.tokenbalance.com/token/0x7295bb8709ec1c22b758a8119a4214ffed016323/0x4bfe074965f1e322e539b2f2995d611edc274d10)

Enjoy!

**Comment by onairelav** [comment]
thanks but I do not need it, I work well offline :)

Cordiali saluti,
Valeriano Cossu

Regards,
Valeriano Cossu

mobile IT: (+39) 3315410763
mobile UK1: (+44) 7300010998
mobile UK2: (+44) 7802703740

**Comment by jesuasir007** [comment]
ya , its work fine.
