### ISSUE TITLE
Wrong result of OMG token balance

### ISSUE THREAD

**Issue by changmyeong** [hunterlong/tokenbalance#8]
my ethereum address: 0x01a2FA8d96436d8f962DBc2AE6c5D5316D51ED58
exact result of omg balance: 0.00203999999999997
Your API's result: 203999999999997
(Your API URL: https://api.tokenbalance.com/token/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07/0x01a2FA8d96436d8f962DBc2AE6c5D5316D51ED58)

How do I get exactly result?

**Comment by nanmu42** [comment]
There is a issue when decimal number is not defined as a function.

https://github.com/hunterlong/tokenbalance/blob/7d7db6a74baf82b5979eddbbdb3065beba8e2476/main.go#L163-L167

**Comment by hunterlong** [comment]
hmm... I made a commit that included some tests for OMG. It didn’t work for balances less than 1. I’m still looking into this.

**Comment by hunterlong** [comment]
Alright, **fixed it**. The Token Balance now has correct decimals. (ugh.. Big Int's..). This update has been pushed to all servers on TokenBalance.com

```
"balance": "0.00203999999999997"
```
