### ISSUE TITLE
API not working in browser (origin error)

### ISSUE THREAD

**Issue by thackerronak** [hunterlong/tokenbalance#9]
API not working at client side(browser). 

Failed to load https://api.tokenbalance.com/token/0xa74476443119A942dE498590Fe1f2454d7D4aC0d/0xda0aed568d9a2dbdcbafc1576fedc633d28eee9a: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://fiddle.jshell.net' is therefore not allowed access.

access control error showing.

https://jsfiddle.net/hunterlong/nkqr6064/

<img width="1279" alt="screen shot 2018-05-16 at 10 41 53 am" src="https://user-images.githubusercontent.com/26240401/40097808-e236a1e4-58f5-11e8-9de1-85cf8d53932a.png">

**Comment by hunterlong** [comment]
Issue has been fixed. I enabled CORS for mainnet, testnet, and rinkeby testnet. I have confirmed it to be working on the jsfiddle link. [https://jsfiddle.net/hunterlong/nkqr6064/](https://jsfiddle.net/hunterlong/nkqr6064/)
